# .golangci.yml
run:
  timeout: 5m

linters:
  enable:
    - staticcheck
    - govet
    - ineffassign
  disable:
    - errcheck
    - unused
  exclusions:
    paths:
      - '(.+)_test\.go'
      - 'example'
  settings:
    staticcheck:
      checks:
        - all
        - '-SA1029'
        - '-SA2002'
        - '-SA4006'
        - '-SA2002'
        - '-SA9003'
        - '-S1024'
        - '-ST1000'
        - '-QF1008'
        - '-SA1019'
        - '-QF1011'
        - '-ST1003'
        - '-QF1001'
        - '-ST1020'

version: '2'