name: Pull Request Check

on: [ pull_request ]

jobs:
  compliant:
    runs-on: [ self-hosted, X64, Linux ]
    steps:
      - uses: actions/checkout@v3

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Spell
        uses: crate-ci/typos@v1.13.14

  # 用一个新的、更强大的 linter 作业替换 staticcheck
  linter:
    runs-on: [ self-hosted, X64, Linux ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Run golangci-lint
        # 使用官方的 golangci-lint-action
        uses: golangci/golangci-lint-action@v8
        with:
          # 指定要使用的 golangci-lint 版本
          version: v2.5
